export const APPLICATION_INIT = 'APPLICATION_INIT';
export type APPLICATION_INIT = typeof APPLICATION_INIT;

export const SETUP_AUTHENTICATION = 'SETUP_AUTHENTICATION';
export type SETUP_AUTHENTICATION = typeof SETUP_AUTHENTICATION;

export const SETUP_TOKEN = 'SETUP_TOKEN';
export type SETUP_TOKEN = typeof SETUP_TOKEN;
